menu:
  Home: /
  Archives: /archives

avatar: '/assets/avatar.jpg'
favicon: '/assets/favicon.ico'

github: "https://github.com/y4ngyy"
jianshu: "https://www.jianshu.com/u/bfe22c1bc5e0"
juejin: ""
cnblog: ""
csdn: ""

friends:
  imagemlt: "https://hexo.imagemlt.xyz"
  abc: ""
